# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jcasian <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/05/31 18:04:21 by jcasian           #+#    #+#              #
#    Updated: 2018/05/31 18:09:31 by jcasian          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
C_files = display_file.c


all:
	@gcc -Wall -Wextra -Werror -o $(NAME) $(C_files)
   	
clean:
	@rm -f *.o

fclean: clean
	@rm -f $(NAME)
