# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jcasian <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/05/29 00:06:49 by jcasian           #+#    #+#              #
#    Updated: 2018/05/29 00:22:55 by jcasian          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

SRC = ft_functions.c oper_functions.c do_op.c

all:
	@gcc $(SRC) -Wall -Wextra -Werror -o $(NAME)

clean:
	@rm -f *.o do-op
